front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     ensurance.dev

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /
    host:     doc.ensurance.dev
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     admin.ensurance.dev

api:
    resource: "@ApiBundle/Controller/"
    type:     rest
    prefix:   /
    host:     api.ensurance.dev
assureur:
    resource: "@AssureurBundle/Controller/"
    type:     annotation
    prefix:   /
    host:     admin.ensurance.dev

consta:
    resource: "@ConstaBundle/Controller/"
    type:     annotation
    prefix:   /

api_user:
    resource: "@ApiUserBundle/Controller/"
    type:     rest
    host:     api.ensurance.dev
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
