<?php

namespace AssureurBundle\Repository;

/**
 * AccidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccidentRepository extends \Doctrine\ORM\EntityRepository
{
}
