<?php

namespace AssureurBundle\Repository;


/**
 * AccidentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\NoResultException;
class AccidentRepository extends \Doctrine\ORM\EntityRepository
{
    public function count(){
        $q = $this->createQueryBuilder('a')->select('count(a)')->where('a.deleted = :deleted')
            ->setParameter('deleted',false);
        try{
            return $q->getQuery()->getSingleScalarResult();
        }
        catch (NoResultException $e){
            return $e;
        }
    }

}
