<?php

namespace AssureurBundle\Repository;

/**
 * ChequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChequeRepository extends \Doctrine\ORM\EntityRepository
{
}
