<?php

namespace AssureurBundle\Repository;

/**
 * ConstatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\NoResultException;
class ConstatRepository extends \Doctrine\ORM\EntityRepository
{
    public function count(){
        $q = $this->createQueryBuilder('c')->select('count(c)');

        try{
            return $q->getQuery()->getSingleScalarResult();
        }
        catch (NoResultException $e){
            return $e;
        }
    }
}
