<?php

namespace AssureurBundle\Repository;

/**
 * ConstatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstatRepository extends \Doctrine\ORM\EntityRepository
{
}
