<?php

namespace AssureurBundle\Repository;

/**
 * DossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use ApiUserBundle\Entity\User;
use Doctrine\ORM\NoResultException;

class DossierRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserId($user_id){
        $q = $this->createQueryBuilder('d');
        $q->select(array('d','r'))
            ->from('AssureurBundle:Rapport','r')
            ->leftJoin('r.dossier','dd');
        $query = $q->getQuery();
        return $query->getResult();
        try {
            return $q->getArrayResult();
        }
        catch (NoResultException $e){
            return null;
        }

    }

    public function getOne($id){
        $q = $this->createQueryBuilder('d')
            ->select('d')
            ->where('d.id = :id')
            ->setParameter('id',$id)
            ->getQuery();
        try {
            return $q->getSingleResult();
        }
        catch (NoResultException $e){
            return null;
        }
    }
}
