<?php

namespace AssureurBundle\Repository;
use Doctrine\ORM\NoResultException;
use Doctrine\ORM\Query;
/**
 * RapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOne($id){
        $q = $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.id = :id')
            ->setParameter('id',$id)
            ->getQuery();
        try {
            return $q->getSingleResult();
        }
        catch (NoResultException $e){
            return null;
        }
    }
}
