<?php

namespace ApiUserBundle\Repository;

/**
 * PermisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermisRepository extends \Doctrine\ORM\EntityRepository
{
}
