<?php

namespace ApiUserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use ApiUserBundle\Entity\User;

class UserRepository extends \Doctrine\ORM\EntityRepository {

    public function findByTest() {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
                ->from('ApiUserBundle:User', 'u');

        return $qb->getQuery()->getResult();
    }

}
