<?php

namespace ApiUserBundle\Repository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\NoResultException;
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function count()
    {
        $q = $this->createQueryBuilder('u')
            ->select('count(u.id)');
        try
        {
            return $q->getQuery()->getSingleScalarResult();
        }
        catch (NoResultException $e){
            return $e;
        }
    }

    public function allUsers(){
        $q = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.deleted = :deleted')
            ->setParameter('deleted',false);
        try
        {
            return $q->getQuery()->getArrayResult();
        }
        catch (NoResultException $e){
            return $e;
        }
    }
}
